#!/usr/bin/env python
import os
import sys
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings.dev")
root_path = os.path.abspath(os.path.split(__file__)[0])
root_path = os.path.join(root_path, "../..")
sys.path.insert(0, os.path.join(root_path, 'trip-planner'))
sys.path.insert(0, root_path)
import django
django.setup()

from django.conf import settings
from django.core.files import File
from apps.routes.models import TracksFile, Route
from scrapers.trailpeak import ScrapeTrailPeak

data_dir = os.path.join(settings.BASE_DIR, "data/ScrapeTrailPeak")


def load_file(filepath):
    with open(filepath) as f:
        name = os.path.basename(filepath)

        qs1 = TracksFile.objects.filter(filename=name)
        qs1_exists = qs1.exists()
        tf = qs1[0] if qs1.exists() else TracksFile.objects.create(tracks_file=File(f, name=name), filename=name)

        qs2 = Route.objects.filter(name=name)
        qs2_exists = qs2.exists()
        route = qs2[0] if qs2.exists() else Route.objects.create_from_route(tf, name)

        print route.id,  qs1_exists,  qs2_exists, name
        return route


if __name__ == "__main__":
    # Route.objects.all().delete()
    # TracksFile.objects.all().delete()
    for filepath in ScrapeTrailPeak().filepaths():
        try:
            load_file(filepath)
        except Exception as e:
            print e
            print filepath

