# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-31 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
