# Generated by Django 2.1.5 on 2019-03-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_auto_20190312_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='routemetadata',
            name='mountain_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routemetadata',
            name='source_gpx_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routemetadata',
            name='source_image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routemetadata',
            name='suggested_gear',
            field=models.TextField(blank=True, null=True),
        ),
    ]
