#!/bin/bash
source <(sed -E -n 's/[^#]+/export &/ p' scripts/.env)

docker build . -t triptracks
docker tag triptracks us.gcr.io/$TP_GOOGLE_PROJECT_ID/triptracks:hello_world
docker push us.gcr.io/$TP_GOOGLE_PROJECT_ID/triptracks:hello_world

gcloud compute instances create triptracks-instance \
    --image-family=debian-8 \
    --image-project=debian-cloud \
    --machine-type=g1-small \
    --scopes userinfo-email,cloud-platform \
    --metadata-from-file startup-script=scripts/run \
    --zone us-central1-f \
    --tags http-server

gcloud compute firewall-rules create default-allow-http-80 \
    --allow tcp:80 \
    --source-ranges 0.0.0.0/0 \
    --target-tags http-server \
    --description "Allow port 80 access to http-server"