#!/usr/bin/env python
import django
django.setup()

import requests
from apps.routes.stores.gpx import GPXS3Store
from apps.routes.models.route_metadata import RouteMetadata


for route in RouteMetadata.objects.all():
    print(route.pub_id)
    if route.source_gpx_url is not None:
        print(route.source_gpx_url)
        resp = requests.get(route.source_gpx_url)
        GPXS3Store().put("%s.gpx" % route.pub_id, resp.content)
