# Generated by Django 2.1.5 on 2019-01-09 20:24

from django.db import migrations, models
import jsonfield.fields
from utils.fields import ShortUUIDField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StravaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_id', ShortUUIDField(max_length=128)),
                ('user_pub_id', models.CharField(max_length=128)),
                ('access_token', models.CharField(max_length=256)),
                ('strava_athlete_id', models.IntegerField()),
                ('attributes', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='StravaActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_id', ShortUUIDField(max_length=128)),
                ('strava_account_pub_id', models.CharField(max_length=128)),
                ('strava_id', models.IntegerField()),
                ('route_pub_id', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
