# Generated by Django 2.2.3 on 2019-08-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravaactivity',
            name='strava_id',
            field=models.BigIntegerField(),
        ),
    ]
