# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 07:17
from __future__ import unicode_literals

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0002_item_pub_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pub_id',
            field=utils.fields.ShortUUIDField(max_length=32),
        ),
    ]
