# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-24 06:42
from __future__ import unicode_literals

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0003_auto_20180328_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglist',
            name='pub_id',
            field=utils.fields.ShortUUIDField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
