# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-24 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0005_auto_20180424_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packinglistitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='packinglistitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='packinglistitem',
            name='original_name',
        ),
        migrations.RemoveField(
            model_name='packinglistitem',
            name='packing_list',
        ),
        migrations.AddField(
            model_name='packinglistitem',
            name='item_pub_id',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packinglistitem',
            name='packing_list_pub_id',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
