# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-02 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0006_auto_20180424_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='route',
        ),
        migrations.AddField(
            model_name='packinglist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packinglist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Itinerary',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
