# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-24 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StravaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_id', utils.fields.ShortUUIDField(max_length=128)),
                ('user_pub_id', models.CharField(max_length=128)),
                ('access_token', models.CharField(max_length=256)),
                ('attributes', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='StravaActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_id', utils.fields.ShortUUIDField(max_length=128)),
                ('strava_account_pub_id', models.CharField(max_length=128)),
                ('route_pub_id', models.CharField(max_length=128)),
            ],
        ),
    ]
