# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_auto_20181024_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaaccount',
            name='strava_account_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
