# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-22 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_id', utils.fields.ShortUUIDField(max_length=32)),
                ('name', models.CharField(max_length=256)),
                ('summary', models.TextField(blank=True, null=True)),
                ('route_pub_id', models.CharField(max_length=32)),
                ('packing_list_pub_id', models.CharField(max_length=32)),
            ],
        ),
    ]
