# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20181018_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_pub_id', models.CharField(max_length=32)),
                ('user_pub_id', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='user_pub_id',
            field=models.CharField(default='user_3ffrCPmfjrQwrbh9FcKXcYqV', max_length=128),
            preserve_default=False,
        ),
    ]
