# Generated by Django 2.1.5 on 2019-01-09 20:24

import django.contrib.auth.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from utils.fields import ShortUUIDField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('google_credentials', django.contrib.postgres.fields.jsonb.JSONField()),
                ('email', models.CharField(max_length=256, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('pub_id', ShortUUIDField(max_length=128)),
                ('send_invitation_emails', models.BooleanField(default=True)),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
