# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 21:03
from __future__ import unicode_literals

import apps.routes.models.tracks_file
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import jsonfield.fields
import utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_id', utils.fields.ShortUUIDField(max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('markers', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('lines', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('lines_zoom_1', jsonfield.fields.JSONField()),
                ('lines_zoom_2', jsonfield.fields.JSONField()),
                ('lines_zoom_3', jsonfield.fields.JSONField()),
                ('lines_zoom_4', jsonfield.fields.JSONField()),
                ('lines_zoom_5', jsonfield.fields.JSONField()),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='TracksFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracks_file', models.FileField(upload_to=apps.routes.models.tracks_file.tracks_file_path)),
                ('filename', models.CharField(max_length=32)),
            ],
        ),
    ]
