# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 20:42
from __future__ import unicode_literals

import apps.routes.models.tracks_file
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('markers', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('lines', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='TracksFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracks_file', models.FileField(upload_to=apps.routes.models.tracks_file.tracks_file_path)),
            ],
        ),
    ]
