# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-20 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20180318_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.CharField(default=b'', max_length=16384),
        ),
        migrations.AddField(
            model_name='route',
            name='image_url',
            field=models.CharField(default=b'', max_length=2048),
        ),
    ]
