# Generated by Django 2.1.5 on 2019-03-12 05:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_routemetadata_geohash'),
    ]

    operations = [
        migrations.AddField(
            model_name='routemetadata',
            name='bounds',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
