# Generated by Django 2.1.5 on 2019-04-03 02:48

from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_auto_20190317_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketListRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_id', utils.fields.ShortUUIDField(db_index=True, max_length=38)),
                ('route_pub_id', models.CharField(max_length=38)),
                ('user_pub_id', models.CharField(max_length=128)),
            ],
        ),
    ]
