# Generated by Django 2.2.3 on 2019-07-17 19:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_bucketlistroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_id', utils.fields.ShortUUIDField(max_length=32)),
                ('owner_pub_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=32768)),
                ('lines', django.contrib.postgres.fields.jsonb.JSONField()),
                ('is_public', models.BooleanField()),
                ('geohash', models.CharField(max_length=32)),
                ('zoom', models.IntegerField()),
                ('bounds', django.contrib.postgres.fields.jsonb.JSONField()),
                ('source_image_url', models.CharField(max_length=8192)),
            ],
        ),
    ]
