# Generated by Django 2.2.3 on 2019-08-01 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0010_route'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
    ]
