# Generated by Django 2.2.3 on 2019-08-23 20:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0012_auto_20190802_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_pub_id', models.CharField(max_length=32)),
                ('zoom', models.IntegerField()),
                ('lines', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'unique_together': {('route_pub_id', 'zoom')},
            },
        ),
    ]
