# Generated by Django 2.2.3 on 2019-08-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0013_routeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeline',
            name='route_pub_id',
            field=models.CharField(max_length=38),
        ),
    ]
