# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-24 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaactivity',
            name='strava_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stravaactivity',
            name='route_pub_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
