# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_stravaaccount_strava_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stravaaccount',
            old_name='strava_account_id',
            new_name='strava_athlete_id',
        ),
    ]
