# Generated by Django 2.1.5 on 2019-01-09 20:24

from django.db import migrations, models
import jsonfield.fields
from utils.fields import ShortUUIDField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_id', ShortUUIDField(max_length=32)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('href', models.URLField()),
                ('img_href', models.URLField()),
                ('attributes', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_id', ShortUUIDField(max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackingListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_pub_id', models.CharField(max_length=256)),
                ('packing_list_pub_id', models.CharField(max_length=256)),
                ('item_type', models.CharField(choices=[('G', 'Group'), ('P', 'Personal')], default='P', max_length=2)),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
