# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-24 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_auto_20180520_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='route',
            name='owner_pub_id',
            field=models.CharField(default=b'user_system', max_length=128),
        ),
    ]
