# Generated by Django 2.1.5 on 2019-02-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20190216_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='routemetadata',
            name='geohash',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
