# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_invitation_emails',
            field=models.BooleanField(default=True),
        ),
    ]
