# Generated by Django 2.2.3 on 2019-08-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_delete_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='routemetadata',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='routemetadata',
            name='owner_pub_id',
            field=models.CharField(default='user_3ffrCPmfjrQwrbh9FcKXcYqV', max_length=128),
        ),
        migrations.AlterField(
            model_name='routemetadata',
            name='source',
            field=models.CharField(choices=[('summitpost', 'Summitpost'), ('trailpeak', 'Trailpeak'), ('strava', 'Strava')], max_length=16),
        ),
    ]
