#!/usr/bin/env python
import django
django.setup()
import pprint
from scrapers.summitpost_route_details import ScrapeSummitPostRouteDetails
from scrapers.trailpeak_route_details import ScrapeTrailPeakDetails


def get_or_create_route(data):
    pprint.pprint(data)
    print()


if __name__ == "__main__":
    sp_scraper = ScrapeSummitPostRouteDetails()
    tp_scraper = ScrapeTrailPeakDetails()
    scrapers = [sp_scraper, tp_scraper]

    for scraper in scrapers:
        print(scraper.__class__.__name__)
        for data in scraper.json_items():
            get_or_create_route(data)
            break
        print()