# Generated by Django 2.1.5 on 2019-01-09 20:25

from django.db import migrations, models
from utils.fields import ShortUUIDField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_id', ShortUUIDField(max_length=32)),
                ('user_pub_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=256)),
                ('summary', models.TextField(blank=True, null=True)),
                ('route_pub_id', models.CharField(max_length=32, null=True)),
                ('packing_list_pub_id', models.CharField(max_length=32, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_pub_id', models.CharField(max_length=32)),
                ('user_pub_id', models.CharField(max_length=128)),
            ],
        ),
    ]
