# Generated by Django 2.2.3 on 2019-07-17 17:27

import datetime
from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sessiontoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 17, 17, 27, 42, 155530)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessiontoken',
            name='pub_id',
            field=utils.fields.ShortUUIDField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessiontoken',
            name='session_key',
            field=utils.fields.ShortUUIDField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessiontoken',
            name='user_pub_id',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
